<link rel="stylesheet" href="{{asset('assets/css/style.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/slide-box.css')}}" type="text/css"> 
<link rel="stylesheet" href="{{asset('assets/css/elmnt-slide.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/elmnt-header.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/elmnt-footer.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/search-bar.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/elmnt-home.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/card-box.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/elmnt-card.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('assets/css/icon-burger.css')}}" type="text/css">